### ISSUE TITLE
Height button usage

### ISSUE THREAD

**Issue by tomyitav** [shubh261096/measurementapp#1]
Hi @shubh261096, thanks for creating this awesome project!
Regarding the height button- can you further explain about what  is shown when clicking on the AR Plane?  I am not entirely sure I understood what height we measure.
Thanks in advance!
Tom

**Comment by shubh261096** [comment]
Hi @tomyitav, 
To measure the height of the object, I rendered a cube of particular width, height & length and when you scale the cube using pinch gesture to the height of the object, the new height is calculated in real-world coordinates.

To simply explain, render a cube of know height and then using pinch gesture, scale the cube to the height of object and since you already know the measurement in real world co-ordinates. You can show it or calculate it.

**Comment by tomyitav** [comment]
Thanks :-)
